export const SET_IS_LOADING = 'SET_IS_LOADING';
export const ERROR_HAPPENED = 'ERROR_HAPPENED';

// PRESENT
export const REFRESH_NOTIFICATION_PRESENT = 'REFRESH_LIST_PRESENT';
export const RESPONSE_INVITATION_PRESENT = 'RESPONSE_INVITATION_PRESENT';

// CONTACT
export const REFRESH_NOTIFICATION_CONTACT = 'REFRESH_LIST_CONTACT';
export const RESPONSE_INVITATION_CONTACT = 'RESPONSE_INVITATION_EVENT';

// EVENT
export const REFRESH_NOTIFICATION_EVENT = 'RESPONSE_NOTIFICATION_EVENT';
export const RESPONSE_INVITATION_EVENT = 'RESPONSE_INVITATION_EVENT';
